import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import { getFirestore, collection, getDocs, query, orderBy } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import { firebaseConfig } from "./firebase.js";
const firebaseApp = initializeApp(firebaseConfig);
const db = getFirestore(firebaseApp);
const auth = getAuth(firebaseApp);
const questionsLabels = { accueil_visite:"Accueil lors de la visite", accueil_telephonique:"Accueil téléphonique", temps_attente:"Temps d'attente", confort_proprete:"Confort et propreté", delai_resultats:"Délai de remise des résultats", satisfaction_globale:"Satisfaction globale" };
let allResponses=[];
const loginBox=document.getElementById("loginBox"),dashboard=document.getElementById("dashboard"),loginError=document.getElementById("loginError");
document.getElementById("loginBtn").addEventListener("click",login);
document.getElementById("logoutBtn").addEventListener("click",()=>signOut(auth));
document.getElementById("exportBtn").addEventListener("click",exportCsv);
onAuthStateChanged(auth,async user=>{ if(user){ loginBox.classList.add("hidden"); dashboard.classList.remove("hidden"); await loadDashboard(); } else { dashboard.classList.add("hidden"); loginBox.classList.remove("hidden"); }});
async function login(){ loginError.textContent=""; const email=document.getElementById("email").value.trim(); const password=document.getElementById("password").value; try{ await signInWithEmailAndPassword(auth,email,password); }catch(e){ console.error(e); loginError.textContent="Email ou mot de passe incorrect."; }}
async function loadDashboard(){ const q=query(collection(db,"responses"),orderBy("localSubmittedAt","desc")); const snap=await getDocs(q); allResponses=snap.docs.map(doc=>({id:doc.id,...doc.data()})); renderStats(); }
function renderStats(){ const total=allResponses.length; document.getElementById("totalResponses").textContent=total; if(!total){ document.getElementById("globalSatisfaction").textContent="0%"; document.getElementById("averageScore").textContent="0/5"; document.getElementById("questionStats").innerHTML="<p>Aucune réponse pour le moment.</p>"; return; } const avg=allResponses.reduce((sum,r)=>sum+Number(r.scoreAverage||0),0)/total; const percent=Math.round((avg/5)*100); document.getElementById("globalSatisfaction").textContent=`${percent}%`; document.getElementById("averageScore").textContent=`${avg.toFixed(2)}/5`; const stats={}; Object.keys(questionsLabels).forEach(key=>{ const scores=allResponses.map(r=>Number(r.answers?.[key]||0)).filter(Boolean); stats[key]=scores.length?scores.reduce((a,b)=>a+b,0)/scores.length:0; }); document.getElementById("questionStats").innerHTML=Object.entries(stats).map(([key,avg])=>{const p=Math.round((avg/5)*100); return `<div class="question-row"><label>${questionsLabels[key]} — ${avg.toFixed(2)}/5 (${p}%)</label><div class="bar"><span style="width:${p}%"></span></div></div>`;}).join(""); }
function exportCsv(){ if(!allResponses.length)return; const header=["date","source","scoreAverage","satisfactionPercent",...Object.keys(questionsLabels)]; const rows=allResponses.map(r=>[r.localSubmittedAt||"",r.source||"",r.scoreAverage||"",r.satisfactionPercent||"",...Object.keys(questionsLabels).map(key=>r.answers?.[key]??"")]); const csv=[header,...rows].map(row=>row.map(value=>`"${String(value).replace(/"/g,'""')}"`).join(",")).join("\n"); const blob=new Blob([csv],{type:"text/csv;charset=utf-8"}); const url=URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url; a.download=`satisfaction-amana-${new Date().toISOString().slice(0,10)}.csv`; a.click(); URL.revokeObjectURL(url); }
